// automatically generated by the FlatBuffers compiler, do not modify

/**
 * @const
*/
var fbs = fbs || {};

/**
 * @const
*/
fbs.messaging = fbs.messaging || {};

/**
 * @enum
 */
fbs.Action = {
  NONE: 0,
  ChatCreate: 1,
  ChatUpdateTitle: 2,
  ChatAddUsers: 3,
  ChatRemoveUsers: 4,
  ChatLock: 5,
  ChatListBefore: 6,
  ChatListAfter: 7,
  ChatGetReadUpTo: 8,
  ChatSetReadUpTo: 9,
  MessageSend: 10,
  MessageUpdateTitle: 11,
  MessageUpdateMedia: 12,
  MessageDelete: 13,
  MessageListBefore: 14,
  MessageListAfter: 15
};

/**
 * @constructor
 */
fbs.Request = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {fbs.Request}
 */
fbs.Request.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {fbs.Request=} obj
 * @returns {fbs.Request}
 */
fbs.Request.getRootAsRequest = function(bb, obj) {
  return (obj || new fbs.Request).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array}
 */
fbs.Request.prototype.id = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array}
 */
fbs.Request.prototype.token = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @returns {fbs.Action}
 */
fbs.Request.prototype.actionType = function() {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? /** @type {fbs.Action} */ (this.bb.readUint8(this.bb_pos + offset)) : fbs.Action.NONE;
};

/**
 * @param {flatbuffers.Table} obj
 * @returns {?flatbuffers.Table}
 */
fbs.Request.prototype.action = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 10);
  return offset ? this.bb.__union(obj, this.bb_pos + offset) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
fbs.Request.startRequest = function(builder) {
  builder.startObject(4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} idOffset
 */
fbs.Request.addId = function(builder, idOffset) {
  builder.addFieldOffset(0, idOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} tokenOffset
 */
fbs.Request.addToken = function(builder, tokenOffset) {
  builder.addFieldOffset(1, tokenOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {fbs.Action} actionType
 */
fbs.Request.addActionType = function(builder, actionType) {
  builder.addFieldInt8(2, actionType, fbs.Action.NONE);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} actionOffset
 */
fbs.Request.addAction = function(builder, actionOffset) {
  builder.addFieldOffset(3, actionOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
fbs.Request.endRequest = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} offset
 */
fbs.Request.finishRequestBuffer = function(builder, offset) {
  builder.finish(offset);
};

// Exports for Node.js and RequireJS
this.fbs = fbs;
