// automatically generated by the FlatBuffers compiler, do not modify

/**
 * @const
*/
var fbs = fbs || {};

/**
 * @const
*/
fbs.messaging = fbs.messaging || {};

/**
 * @enum
 */
fbs.ErrorCode = {
  Auth: 0,
  Refusal: 1,
  SendLimit: 2,
  ReceiveLimit: 3,
  Balance: 4,
  InvalidRequest: 5
};

/**
 * @enum
 */
fbs.Action = {
  NONE: 0,
  Error: 1,
  Created: 2,
  Updated: 3,
  ChatList: 4,
  ReadUpTo: 5,
  MessageList: 6
};

/**
 * @constructor
 */
fbs.Error = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {fbs.Error}
 */
fbs.Error.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {fbs.Error=} obj
 * @returns {fbs.Error}
 */
fbs.Error.getRootAsError = function(bb, obj) {
  return (obj || new fbs.Error).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {fbs.ErrorCode}
 */
fbs.Error.prototype.code = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? /** @type {fbs.ErrorCode} */ (this.bb.readInt8(this.bb_pos + offset)) : fbs.ErrorCode.Auth;
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array}
 */
fbs.Error.prototype.text = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
fbs.Error.startError = function(builder) {
  builder.startObject(2);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {fbs.ErrorCode} code
 */
fbs.Error.addCode = function(builder, code) {
  builder.addFieldInt8(0, code, fbs.ErrorCode.Auth);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} textOffset
 */
fbs.Error.addText = function(builder, textOffset) {
  builder.addFieldOffset(1, textOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
fbs.Error.endError = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
fbs.Updated = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {fbs.Updated}
 */
fbs.Updated.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {fbs.Updated=} obj
 * @returns {fbs.Updated}
 */
fbs.Updated.getRootAsUpdated = function(bb, obj) {
  return (obj || new fbs.Updated).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Builder} builder
 */
fbs.Updated.startUpdated = function(builder) {
  builder.startObject(0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
fbs.Updated.endUpdated = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
fbs.Created = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {fbs.Created}
 */
fbs.Created.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {fbs.Created=} obj
 * @returns {fbs.Created}
 */
fbs.Created.getRootAsCreated = function(bb, obj) {
  return (obj || new fbs.Created).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array}
 */
fbs.Created.prototype.id = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
fbs.Created.startCreated = function(builder) {
  builder.startObject(1);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} idOffset
 */
fbs.Created.addId = function(builder, idOffset) {
  builder.addFieldOffset(0, idOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
fbs.Created.endCreated = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
fbs.Response = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {fbs.Response}
 */
fbs.Response.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {fbs.Response=} obj
 * @returns {fbs.Response}
 */
fbs.Response.getRootAsResponse = function(bb, obj) {
  return (obj || new fbs.Response).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array}
 */
fbs.Response.prototype.id = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @returns {fbs.Action}
 */
fbs.Response.prototype.actionType = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? /** @type {fbs.Action} */ (this.bb.readUint8(this.bb_pos + offset)) : fbs.Action.NONE;
};

/**
 * @param {flatbuffers.Table} obj
 * @returns {?flatbuffers.Table}
 */
fbs.Response.prototype.action = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? this.bb.__union(obj, this.bb_pos + offset) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
fbs.Response.startResponse = function(builder) {
  builder.startObject(3);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} idOffset
 */
fbs.Response.addId = function(builder, idOffset) {
  builder.addFieldOffset(0, idOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {fbs.Action} actionType
 */
fbs.Response.addActionType = function(builder, actionType) {
  builder.addFieldInt8(1, actionType, fbs.Action.NONE);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} actionOffset
 */
fbs.Response.addAction = function(builder, actionOffset) {
  builder.addFieldOffset(2, actionOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
fbs.Response.endResponse = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} offset
 */
fbs.Response.finishResponseBuffer = function(builder, offset) {
  builder.finish(offset);
};

// Exports for Node.js and RequireJS
this.fbs = fbs;
