var path = require('path');
var fs = require('fs');

module.exports = {
  accordion: fs.readFileSync(path.join(__dirname, '../fat-ui', 'Accordion.js'), 'utf8'),
  badgeCollections: fs.readFileSync(path.join(__dirname, '../fat-ui', 'BadgeCollections.js'), 'utf8'),
  badgeDropdowns: fs.readFileSync(path.join(__dirname, '../fat-ui', 'BadgeDropdowns.js'), 'utf8'),
  badgeNavbar: fs.readFileSync(path.join(__dirname, '../fat-ui', 'BadgeNavbar.js'), 'utf8'),
  breadcrumb: fs.readFileSync(path.join(__dirname, '../fat-ui', 'Breadcrumbs.js'), 'utf8'),
  cardImage: fs.readFileSync(path.join(__dirname, '../fat-ui', 'CardImage.js'), 'utf8'),
  cardPanel: fs.readFileSync(path.join(__dirname, '../fat-ui', 'CardPanel.js'), 'utf8'),
  cardReveal: fs.readFileSync(path.join(__dirname, '../fat-ui', 'CardReveal.js'), 'utf8'),
  cardSimple: fs.readFileSync(path.join(__dirname, '../fat-ui', 'CardSimple.js'), 'utf8'),
  chips: fs.readFileSync(path.join(__dirname, '../fat-ui', 'Chips.js'), 'utf8'),
  collapsible: fs.readFileSync(path.join(__dirname, '../fat-ui', 'Collapsible.js'), 'utf8'),
  collectionBasic: fs.readFileSync(path.join(__dirname, '../fat-ui', 'CollectionBasic.js'), 'utf8'),
  collectionWithHeader: fs.readFileSync(path.join(__dirname, '../fat-ui', 'CollectionWithHeader.js'), 'utf8'),
  collectionWithHref: fs.readFileSync(path.join(__dirname, '../fat-ui', 'CollectionWithHref.js'), 'utf8'),
  disabledButton: fs.readFileSync(path.join(__dirname, '../fat-ui', 'DisabledButton.js'), 'utf8'),
  dropdown: fs.readFileSync(path.join(__dirname, '../fat-ui', 'DropdownBasic.js'), 'utf8'),
  fixedActionButton: fs.readFileSync(path.join(__dirname, '../fat-ui', 'FixedActionButton.js'), 'utf8'),
  flatButton: fs.readFileSync(path.join(__dirname, '../fat-ui', 'FlatButton.js'), 'utf8'),
  floatingButton: fs.readFileSync(path.join(__dirname, '../fat-ui', 'FloatingButton.js'), 'utf8'),
  footer: fs.readFileSync(path.join(__dirname, '../fat-ui', 'Footer.js'), 'utf8'),
  grid: fs.readFileSync(path.join(__dirname, '../fat-ui', 'Grid.js'), 'utf8'),
  horizontalFab: fs.readFileSync(path.join(__dirname, '../fat-ui', 'HorizontalFAB.js'), 'utf8'),
  iconLinksNavbar: fs.readFileSync(path.join(__dirname, '../fat-ui', 'IconLinksNavbar.js'), 'utf8'),
  iconPrefixesInput: fs.readFileSync(path.join(__dirname, '../fat-ui', 'IconPrefixesInput.js'), 'utf8'),
  inputCheckbox: fs.readFileSync(path.join(__dirname, '../fat-ui', 'InputCheckbox.js'), 'utf8'),
  inputFields: fs.readFileSync(path.join(__dirname, '../fat-ui', 'InputFields.js'), 'utf8'),
  inputRadio: fs.readFileSync(path.join(__dirname, '../fat-ui', 'InputRadio.js'), 'utf8'),
  inputSwitch: fs.readFileSync(path.join(__dirname, '../fat-ui', 'InputSwitch.js'), 'utf8'),
  largeButton: fs.readFileSync(path.join(__dirname, '../fat-ui', 'LargeButton.js'), 'utf8'),
  leftAlignedNavbar: fs.readFileSync(path.join(__dirname, '../fat-ui', 'LeftAlignedNavbar.js'), 'utf8'),
  mediaBox: fs.readFileSync(path.join(__dirname, '../fat-ui', 'MediaBox.js'), 'utf8'),
  modal: fs.readFileSync(path.join(__dirname, '../fat-ui', 'Modal.js'), 'utf8'),
  modalWithBottomSheet: fs.readFileSync(path.join(__dirname, '../fat-ui', 'ModalWithBottomSheet.js'), 'utf8'),
  modalWithFixedFooter: fs.readFileSync(path.join(__dirname, '../fat-ui', 'ModalWithFixedFooter.js'), 'utf8'),
  pagination: fs.readFileSync(path.join(__dirname, '../fat-ui', 'Pagination.js'), 'utf8'),
  prefillingTextInput: fs.readFileSync(path.join(__dirname, '../fat-ui', 'PrefillingTextInput.js'), 'utf8'),
  preloaderCircular: fs.readFileSync(path.join(__dirname, '../fat-ui', 'PreloaderCircular.js'), 'utf8'),
  progressBars: fs.readFileSync(path.join(__dirname, '../fat-ui', 'ProgressBars.js'), 'utf8'),
  raisedButton: fs.readFileSync(path.join(__dirname, '../fat-ui', 'RaisedButton.js'), 'utf8'),
  rightAlignedNavbar: fs.readFileSync(path.join(__dirname, '../fat-ui', 'RightAlignedNavbar.js'), 'utf8'),
  selectSimple: fs.readFileSync(path.join(__dirname, '../fat-ui', 'SelectSimple.js'), 'utf8'),
  sliders: fs.readFileSync(path.join(__dirname, '../fat-ui', 'Sliders.js'), 'utf8'),
  submitButton: fs.readFileSync(path.join(__dirname, '../fat-ui', 'SubmitButton.js'), 'utf8'),
  tab: fs.readFileSync(path.join(__dirname, '../fat-ui', 'Tab.js'), 'utf8'),
  tableBorderless: fs.readFileSync(path.join(__dirname, '../fat-ui', 'BorderlessTable.js'), 'utf8'),
  toast: fs.readFileSync(path.join(__dirname, '../fat-ui', 'Toast.js'), 'utf8'),
};
